@CurrencyConverter.Api_HostAddress = http://localhost:5295

GET {{CurrencyConverter.Api_HostAddress}}/health

###

GET {{CurrencyConverter.Api_HostAddress}}/api/v1/languages
Accept: application/json

###

POST {{CurrencyConverter.Api_HostAddress}}/api/v1/currency/convert
Content-Type: application/json

{
  "amount": "25,1",
  "language": "en"
}

###
